print("NOMBRE: BruceGarate/n")
nombre = input("Introducir su nombre: ")
print("OPCION 1")
print("!HOLA: " + nombre + "|")
print("OPCION 2")
print("!HOLA: {nombre}")
print("OPCION 3")
print("!HOLA: {}".format (nombre))
print("OPCION 4")
print("!HOLA: ", nombre)